"""
DINOv3 Vision Encoder with Task-Specific LoRA Adapters (HyperCT Style)

Encodes 2D CT slices using DINOv3 (DINOv2 with registers), applies task-specific
LoRA weights generated by a hypernetwork conditioned on task embeddings.

DINOv3 adds register tokens to DINOv2 that absorb high-norm artifacts and
produce cleaner, more spatially coherent feature maps — critical for
medical imaging where fine-grained spatial detail matters.

Architecture:
    CT Slice (H, W) → DINOv3 → patch tokens (N_patches, 768)
                     ↑
            Task-specific LoRA weights from HyperNetwork

References:
    - DINOv3 (DINOv2 with registers): https://arxiv.org/abs/2309.16588
    - HyperCT: https://openreview.net/forum?id=n3VLj8LFz3
    - LoRA: https://arxiv.org/abs/2106.09685
"""

import math
import torch
import torch.nn as nn
from transformers import AutoModel, AutoImageProcessor
from typing import Dict, Optional


class LoRALinear(nn.Module):
    """LoRA-adapted linear layer. Accepts externally-generated A/B matrices."""

    def __init__(self, base_linear: nn.Linear, rank: int = 16, alpha: int = 32):
        super().__init__()
        self.base = base_linear
        self.base.requires_grad_(False)
        self.rank = rank
        self.scaling = alpha / rank
        self.in_features = base_linear.in_features
        self.out_features = base_linear.out_features

    def forward(self, x: torch.Tensor, lora_A: torch.Tensor, lora_B: torch.Tensor) -> torch.Tensor:
        base_out = self.base(x)
        lora_out = (x @ lora_A.T) @ lora_B.T * self.scaling
        return base_out + lora_out


class HyperNetwork(nn.Module):
    """
    Generates task-specific LoRA weights from a task embedding.

    Input: task_id → task_embedding → MLP → LoRA weights (A, B) for each target module
    """

    def __init__(self, num_tasks: int, task_embed_dim: int, hidden_dim: int,
                 target_modules: Dict[str, tuple], lora_rank: int):
        super().__init__()
        self.task_embeddings = nn.Embedding(num_tasks, task_embed_dim)
        self.lora_rank = lora_rank
        self.target_modules = target_modules

        self.shared_mlp = nn.Sequential(
            nn.LayerNorm(task_embed_dim),
            nn.Linear(task_embed_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
        )

        # Per-module heads: each outputs flattened (A, B) for one target module
        self.heads = nn.ModuleDict()
        for name, (in_f, out_f) in target_modules.items():
            total_params = lora_rank * in_f + lora_rank * out_f
            self.heads[name] = nn.Linear(hidden_dim, total_params)

    def forward(self, task_id: torch.Tensor) -> Dict[str, tuple]:
        """
        Args:
            task_id: (1,) or scalar tensor with task index
        Returns:
            dict mapping module_name → (lora_A, lora_B)
            lora_A: (rank, in_features), lora_B: (out_features, rank)
        """
        emb = self.task_embeddings(task_id)
        h = self.shared_mlp(emb).squeeze(0)

        lora_weights = {}
        for name, (in_f, out_f) in self.target_modules.items():
            params = self.heads[name](h)
            a_size = self.lora_rank * in_f
            lora_A = params[:a_size].view(self.lora_rank, in_f)
            lora_B = params[a_size:].view(out_f, self.lora_rank)
            lora_weights[name] = (lora_A, lora_B)

        return lora_weights


class DINOv3LoRAEncoder(nn.Module):
    """
    DINOv3 (DINOv2 with registers) encoder with HyperNetwork-generated
    task-specific LoRA adapters.

    DINOv3 adds 4 register tokens that act as global memory, reducing
    artifacts in attention maps and improving feature quality for
    dense prediction tasks like medical image analysis.

    For each 2D slice and each task:
        1. DINOv3 extracts patch tokens (registers are dropped)
        2. HyperNetwork generates LoRA (A, B) for attention layers
        3. LoRA modulates attention outputs
        4. Returns per-slice patch tokens

    Output shape per slice: (N_patches, 768)
    """

    NUM_REGISTER_TOKENS = 4

    def __init__(self, encoder_name: str = "facebook/dinov2-with-registers-base",
                 num_tasks: int = 18, task_embed_dim: int = 128,
                 hyper_hidden_dim: int = 256, lora_rank: int = 16,
                 lora_alpha: int = 32):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(encoder_name)
        self.processor = AutoImageProcessor.from_pretrained(encoder_name)
        self.encoder.requires_grad_(False)

        self.lora_rank = lora_rank
        self.lora_alpha = lora_alpha
        self.scaling = lora_alpha / lora_rank

        # Identify target modules (qkv and proj in each ViT block)
        target_modules = {}
        for i, layer in enumerate(self.encoder.encoder.layer):
            attn = layer.attention.attention
            in_dim = attn.query.in_features
            out_dim = attn.query.out_features
            target_modules[f"layer_{i}_qkv"] = (in_dim, out_dim * 3)
            target_modules[f"layer_{i}_proj"] = (out_dim, out_dim)

        self.target_modules = target_modules

        self.hypernet = HyperNetwork(
            num_tasks=num_tasks,
            task_embed_dim=task_embed_dim,
            hidden_dim=hyper_hidden_dim,
            target_modules=target_modules,
            lora_rank=lora_rank,
        )

    @torch.no_grad()
    def _base_forward(self, pixel_values: torch.Tensor) -> torch.Tensor:
        """Standard DINOv3 forward — returns patch tokens (no CLS, no registers)."""
        outputs = self.encoder(pixel_values=pixel_values)
        # DINOv3 output: [CLS, reg1, reg2, reg3, reg4, patch1, patch2, ...]
        return outputs.last_hidden_state[:, 1 + self.NUM_REGISTER_TOKENS:, :]

    def forward_with_lora(self, pixel_values: torch.Tensor,
                          lora_weights: Dict[str, tuple]) -> torch.Tensor:
        """
        Forward with task-specific LoRA applied to attention layers.

        Args:
            pixel_values: (B, 3, H, W)
            lora_weights: from HyperNetwork
        Returns:
            patch_tokens: (B, N_patches, 768)
        """
        # Get embeddings
        embeddings = self.encoder.embeddings(pixel_values)

        hidden = embeddings
        for i, layer in enumerate(self.encoder.encoder.layer):
            # Standard layer forward with LoRA injection
            attn = layer.attention.attention

            # Compute Q, K, V with LoRA
            qkv_key = f"layer_{i}_qkv"
            proj_key = f"layer_{i}_proj"

            residual = hidden
            if hasattr(layer, 'layernorm_before'):
                hidden_normed = layer.layernorm_before(hidden)
            else:
                hidden_normed = layer.norm1(hidden)

            # QKV with LoRA
            q = attn.query(hidden_normed)
            k = attn.key(hidden_normed)
            v = attn.value(hidden_normed)

            if qkv_key in lora_weights:
                lora_A, lora_B = lora_weights[qkv_key]
                lora_A = lora_A.to(hidden_normed.device, dtype=hidden_normed.dtype)
                lora_B = lora_B.to(hidden_normed.device, dtype=hidden_normed.dtype)
                lora_delta = (hidden_normed @ lora_A.T) @ lora_B.T * self.scaling
                d = q.shape[-1]
                q = q + lora_delta[..., :d]
                k = k + lora_delta[..., d:2*d]
                v = v + lora_delta[..., 2*d:]

            # Self-attention
            B, N, C = q.shape
            num_heads = attn.num_attention_heads
            head_dim = C // num_heads
            q = q.view(B, N, num_heads, head_dim).transpose(1, 2)
            k = k.view(B, N, num_heads, head_dim).transpose(1, 2)
            v = v.view(B, N, num_heads, head_dim).transpose(1, 2)

            attn_weights = (q @ k.transpose(-2, -1)) * (head_dim ** -0.5)
            attn_weights = attn_weights.softmax(dim=-1)
            attn_out = (attn_weights @ v).transpose(1, 2).reshape(B, N, C)

            # Output projection with LoRA
            proj_out = layer.attention.output.dense(attn_out)
            if proj_key in lora_weights:
                pA, pB = lora_weights[proj_key]
                pA = pA.to(attn_out.device, dtype=attn_out.dtype)
                pB = pB.to(attn_out.device, dtype=attn_out.dtype)
                proj_out = proj_out + (attn_out @ pA.T) @ pB.T * self.scaling

            proj_out = layer.attention.output.dropout(proj_out)
            hidden = residual + proj_out

            # FFN
            residual = hidden
            if hasattr(layer, 'layernorm_after'):
                hidden_normed = layer.layernorm_after(hidden)
            else:
                hidden_normed = layer.norm2(hidden)

            ffn_out = layer.intermediate.dense(hidden_normed)
            ffn_out = layer.intermediate.intermediate_act_fn(ffn_out)
            ffn_out = layer.output.dense(ffn_out)
            ffn_out = layer.output.dropout(ffn_out)
            hidden = residual + ffn_out

        # Final layernorm
        hidden = self.encoder.layernorm(hidden)
        # Drop CLS + 4 register tokens
        return hidden[:, 1 + self.NUM_REGISTER_TOKENS:, :]

    def encode_slice(self, pixel_values: torch.Tensor,
                     task_id: torch.Tensor) -> torch.Tensor:
        """
        Encode a single slice with task-specific LoRA.

        Args:
            pixel_values: (1, 3, H, W) preprocessed slice
            task_id: scalar tensor with task index
        Returns:
            patch_tokens: (1, N_patches, 768)
        """
        lora_weights = self.hypernet(task_id)
        return self.forward_with_lora(pixel_values, lora_weights)
